# Generated by Django 4.1 on 2023-03-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDOList', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='slug',
            field=models.SlugField(default=2, max_length=250),
            preserve_default=False,
        ),
    ]
