# Generated by Django 4.1 on 2023-03-24 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDOList', '0005_tasks_is_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='is_complete',
        ),
    ]
