# Generated by Django 4.1 on 2023-03-24 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDOList', '0006_remove_tasks_is_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='slug',
            new_name='url',
        ),
    ]
