# Generated by Django 4.1 on 2023-03-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDOList', '0008_rename_url_tasks_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
